##GET
GET http://localhost:4004/odata/v4/user/User

###POST
POST http://localhost:4004/odata/v4/user/User
Content-Type: application/json

{
    "nombre": "jose",
    "apellido": "londoño",
    "correo": "jip12o@gmail.com",
    "password": "#12345WE"
}